version: '3.8'

services:
  # The Inference API Service (GPU-Accelerated)
  api:
    build:
      context: ./app_api
      dockerfile: Dockerfile.api
    container_name: dl_api_server

    # === NVIDIA GPU CONFIGURATION 
    # 1. Specifies the NVIDIA runtime driver (prerequisite: NVIDIA Container Toolkit on host)
    runtime: nvidia
    # 2. Allocates specific GPU resources (using 'all' for simplicity, or 'count: 1')
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    # 3. Allocates sufficient shared memory (critical for PyTorch/DL model loading)
    shm_size: '2gb'
    # ====================================================

    # Expose the port only internally for the GUI to access
    expose:
      - "8000"
    # Optional: If you need to explicitly limit RAM
    # mem_limit: '4g'

    # The Graphical Interface Service
  gui:
    build:
      context: ./app_gui
      dockerfile: Dockerfile.gui
    container_name: gradio_interface
    # This is the only port we expose to your host machine (e.g., your browser)
    ports:
      - "8080:7860" # Map host port 8080 to container port 7860 (Gradio default)

    # Ensures the API is running before the GUI tries to connect
    depends_on:
      - api
